version: 2

sources:
    - name: staging
      database: omega-byte-447718-e2
      schema: redfin_housing_market

      tables:
        - name: staging_national_housing_market_data
        - name: staging_state_housing_market_data
        - name: staging_metro_housing_market_data
        - name: staging_county_housing_market_data
        - name: staging_city_housing_market_data


models:
    - name: stg_monthly_housing_data_union
      description: >
        Housing data for each month across various regions in the US from 2012.
      columns:
          - name: period_begin
            description: Begin period
            data_type: date
            tests:
                - not_null:
                    severity: warn
          - name: period_end
            description: End period
            data_type: date
            tests:
                - not_null:
                    severity: warn
          - name: period_duration 
            data_type: integer
            description: > 
                Duration of the period for which the data point is collected
          - name: region_type 
            description: Type of the region for which the data point is collected
            data_type: string
          - name: region 
            description: The region name (metro, county, city, state etc)
            data_type: string
          - name:	state_code
            data_type: string
          - name:	property_type
            description: Property type description
            data_type: string
          - name:	median_sale_price
            data_type: float
          - name:	median_sale_price_mom
            data_type: float
          - name:	median_sale_price_yoy
            data_type: float
          - name:	median_list_price
            data_type: float
          - name:	median_list_price_mom
            data_type: float
          - name:	median_list_price_yoy
            data_type: float
          - name:	homes_sold
            data_type: float
          - name:	homes_sold_mom
            data_type: float
          - name:	homes_sold_yoy
            data_type: float
          - name:	pending_sales
            data_type: float
          - name:	pending_sales_mom
            data_type: float
          - name:	pending_sales_yoy
            data_type: float
          - name:	new_listings
            data_type: float
          - name:	new_listings_mom
            data_type: float
          - name:	new_listings_yoy
            data_type: float
          - name:	inventory
            data_type: float
          - name:	inventory_mom
            data_type: float
          - name:	inventory_yoy
            data_type: float
          - name:	average_sale_to_list
            data_type: float
          - name:	average_sale_to_list_mom
            data_type: float
          - name:	average_sale_to_list_yoy
            data_type: float
          - name:	sold_above_list
            data_type: float
          - name:	sold_above_list_mom
            data_type: float
          - name:	sold_above_list_yoy
            data_type: float
          - name:	off_market_in_two_weeks
            data_type: float
          - name:	off_market_in_two_weeks_mom
            data_type: float
          - name:	off_market_in_two_weeks_yoy
            data_type: float


